image:
  - Visual Studio 2019
  
configuration:
  - Release
  - Debug
  
environment:
  matrix:
  - PLATFORM: x64
  - PLATFORM: Win32
  
install:  
  - git clone --depth 1 https://github.com/bkaradzic/bx
  - git clone --depth 1 https://github.com/bkaradzic/bimg
  - git clone --depth 1 https://github.com/bkaradzic/bgfx.git

before_build:
- cmd: cd bgfx
- cmd: ..\bx\tools\bin\windows\genie --with-tools --platform=%PLATFORM% vs2019
  
build_script:
- cmd: msbuild .build\projects\vs2019\bgfx.sln /t:Clean,Build /p:Platform=%PLATFORM% /p:Configuration=%CONFIGURATION%
- cmd: cd ..
  
#after_test:
#  - cmd: nuget pack Package-%PLATFORM%-%CONFIGURATION%.nuspec -Version %APPVEYOR_BUILD_VERSION%-%PLATFORM%-%CONFIGURATION%
  
#artifacts:
#  - path: '**\*.nupkg'
  
#deploy:
#- provider: Environment
#  name: production