image:
  - Visual Studio 2019
    
environment:
  matrix:
  - BUILD_PLATFORM: x64
    platform: x64
    CONFIG: Release
    TOOLS:
  - BUILD_PLATFORM: x64
    platform: x64
    CONFIG: Debug
    TOOLS:
  - BUILD_PLATFORM: x32
    platform: Win32
    CONFIG: Release  
    TOOLS:
  - BUILD_PLATFORM: x32
    platform: Win32
    CONFIG: Debug
    TOOLS:
  
install:  
  - git clone --depth 1 https://github.com/bkaradzic/bx
  - git clone --depth 1 https://github.com/bkaradzic/bimg
  - git clone --depth 1 https://github.com/bkaradzic/bgfx.git

before_build:
- cmd: cd bgfx
- cmd: ..\bx\tools\bin\windows\genie %TOOLS% --platform=%BUILD_PLATFORM% vs2019
  
build_script:
- cmd: msbuild .build\projects\vs2019\bgfx.sln /t:Clean,Build /p:Configuration=%CONFIG% /p:Platform=%platform%
- cmd: cd ..
  
#after_test:
#  - cmd: nuget pack Package-%PLATFORM%-%CONFIGURATION%.nuspec -Version %APPVEYOR_BUILD_VERSION%-%PLATFORM%-%CONFIGURATION%
  
#artifacts:
#  - path: '**\*.nupkg'
  
#deploy:
#- provider: Environment
#  name: production