image:
  - Visual Studio 2019
  
install:  
  - git clone --depth 1 https://github.com/bkaradzic/bx
  - git clone --depth 1 https://github.com/bkaradzic/bimg
  - git clone --depth 1 https://github.com/bkaradzic/bgfx.git

before_build:
- cmd: cd bgfx
- cmd: ..\bx\tools\bin\windows\genie --with-tools --platform=x64 vs2019
  
build_script:
- cmd: msbuild .build\projects\vs2019\bgfx.sln /t:Clean,Build /p:Platform=x64 /p:Configuration=Release
- cmd: msbuild .build\projects\vs2019\bgfx.sln /t:Clean,Build /p:Platform=x64 /p:Configuration=Debug
- cmd: cd ..
  
after_test:
  - cmd: nuget pack -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: production